server:
  port: 8810 #服务端口
spring:
  application:
    name: scrms #指定服务名
#  jta:
#    atomikos:
#      properties:
#        log-base-dir: ../logs
#    transaction-manager-id: txManager
  devtools:
    restart:
      enabled=true: true

tn:
  datasource:
    mysql-master:
      name: mysqlMaster
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.52.86:3306/scrms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: line
      #      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
    oracle-master:
      name: oracleMaster
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.51.251:1521:CRMSDEV
      username: tncrms
      password: zscrmstestdb
      #   数据源其他配置
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      poolPreparedStatements: true



#mybatis:
#   mapper-locations: classpath:**/*Mapper.xml
#  type-aliases-package: com.tn.scrms

#
#pagehelper:
#  #  helperDialect: mysql
#  reasonable: false
#  supportMethodsArguments: true
#  params: count=countSql
#  # 默认false,当为true时，自动检验适合的数据库
#  auto-dialect: true
#  # 这个一定要加上，不然mysql和oracle分页两个只能用一个，另一个会报错，加上后，两中数据库分页都可以用了
#  auto-runtime-dialect: true



#配置分页插件pagehelper
pagehelper:
#  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  # 默认false,当为true时，自动检验适合的数据库
  auto-dialect: true
  # 这个一定要加上，不然mysql和oracle分页两个只能用一个，另一个会报错，加上后，两中数据库分页都可以用了
  auto-runtime-dialect: true


# 通用mapper
mapper:
  #公用接口类路径
  mappers: com.tn.scrms.base.IBaseDao
#  identity: MYSQL
#showSql
logging:
  level:
    com:
      tn:
        scrms:
          dao:
            mysql: debug
            oracle: debug

ding:
  operation:
    acct:
      userName: ycs
      passWord: line


